### ISSUE TITLE
Colors not appearing

### ISSUE THREAD

**Issue by DevArqf** [dzhavat/bracket-pair-toggler#2]
I am enabling the extension. but the bracket colors do not appear. I tried manually doing it but nothing works.

**Comment by dzhavat** [comment]
Hey @DevArqf 
Thanks for reporting the issue. May I ask which version of VS Code are you using?

I just tried it on v1.87.2 (latest stable as of 2024-03-13) and it works.

**Comment by DevArqf** [comment]
> Hey @DevArqf 
> Thanks for reporting the issue. May I ask which version of VS Code are you using?
> 
> I just tried it on v1.87.2 (latest stable as of 2024-03-13) and it works. 

I am using the latest version of VS Code as well, I have tried remove the enable part from settings.json then turning the extension on again, I made sure that where I searched "Bracket Colorization", I made sure that that is enabled. I've tried basically everything and now I am clueless. I even tried remove my animated background and changed the theme, but nothing.

**Comment by dzhavat** [comment]
Weird. You've done pretty much everything I can come up with :)

What about disabling the extension and enabling the feature from VS Code Settings.

If this doesn't work, then it's something with VS Code because the only thing this extension does is that it toggles the native `editor.bracketPairColorization.enabled` setting.

![image](https://github.com/dzhavat/bracket-pair-toggler/assets/1096332/8e8c8143-e5f7-4ea2-9518-fc65bd5194d6)

**Comment by DevArqf** [comment]
> Weird. You've done pretty much everything I can come up with :)
> 
> What about disabling the extension and enabling the feature from VS Code Settings.
> 
> If this doesn't work, then it's something with VS Code because the only thing this extension does is that it toggles the native `editor.bracketPairColorization.enabled` setting.
> 
> ![image](https://github.com/dzhavat/bracket-pair-toggler/assets/1096332/8e8c8143-e5f7-4ea2-9518-fc65bd5194d6)

I have disabled the extension and enabled the feature from VS Code but that did not work neither.

If it's an issue with the VS Code itself, how can I fix the issue?

**Comment by dzhavat** [comment]
It I had the same issue, I'd do:
- Disable all extensions to see if that fixes the issue. There's a command for that "Reload with extensions disabled"
- Comment out all user settings and see if that helps
- Comment out all workspace settings and see if that helps

**Comment by DevArqf** [comment]
> It I had the same issue, I'd do:
> - Disable all extensions to see if that fixes the issue. There's a command for that "Reload with extensions disabled"
> - Comment out all user settings and see if that helps
> - Comment out all workspace settings and see if that helps

Alright, I'll try it once I get home and I'll update you.

**Comment by DevArqf** [comment]
> It I had the same issue, I'd do:
> 
> * Disable all extensions to see if that fixes the issue. There's a command for that "Reload with extensions disabled"
> * Comment out all user settings and see if that helps
> * Comment out all workspace settings and see if that helps

I have tried all of these, none of them seem to have worked. Tomorrow I will try and reinstall VSC and install your extension before any other and see if that fixes it. I will keep you updated!

**Comment by DevArqf** [comment]
> It I had the same issue, I'd do:
> 
> * Disable all extensions to see if that fixes the issue. There's a command for that "Reload with extensions disabled"
> * Comment out all user settings and see if that helps
> * Comment out all workspace settings and see if that helps

Hello, I have reinstalled Visual Studio Code and the extensions, nothing seem to have worked. Unfortunately I decided to not use your extension anymore but I am using another and weirdly, the current extension I am using is working fine.

**Comment by dzhavat** [comment]
Hey, thanks for the update. It's funny that the problem persists even after reinstalling VS Code. Maybe some cached settings? Anyway, I'm glad that you found a solution. Thanks for giving my extension a try. Have a nice weekend :)

**Comment by DevArqf** [comment]
> Owner



> Hey, thanks for the update. It's funny that the problem persists even after reinstalling VS Code. Maybe some cached settings? Anyway, I'm glad that you found a solution. Thanks for giving my extension a try. Have a nice weekend :)

Perhaps it was some cached somethings, but at least I have found an solution. I am glad I have also used your Extension to at least try and use it. Have a nice weekend!
